FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]


RUN Invoke-WebRequest 'http://de.apachehaus.com/downloads/httpd-2.4.48-o111l-x64-vc15.zip' -OutFile 'apache.zip'
RUN Expand-Archive apache.zip -DestinationPath C:/
RUN Invoke-WebRequest 'https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe' -OutFile 'vc_redist.x64.exe'
RUN Start-Process '.\vc_redist.x64.exe' '/install /passive /norestart' -Wait
RUN Remove-Item vc_redist.x64.exe
RUN Remove-Item apache.zip

COPY ./dcom/dist/ C:/Apache24/htdocs
COPY ./.htaccess C:/Apache24/htdocs
COPY ./httpd.conf C:/Apache24/conf

EXPOSE 80

CMD [ "C:\\Apache24\\bin\\httpd.exe" ]

